coverage:
  range: "30..80"
  round: down
  precision: 2
  status:
    project: off
    patch: off

ignore:
   - "bboxdb-server/src/main/java/org/bboxdb/performance"
   - "bboxdb-server/src/main/java/org/bboxdb/tools"

