language: java
sudo: false

before_install:
  # Install zookeeper
  - mkdir /tmp/zookeeper
  - wget http://www.eu.apache.org/dist/zookeeper/zookeeper-3.4.8/zookeeper-3.4.8.tar.gz
  - tar xzf zookeeper-3.4.8.tar.gz -C /tmp/zookeeper
  - cp /tmp/zookeeper/zookeeper-3.4.8/conf/zoo_sample.cfg /tmp/zookeeper/zookeeper-3.4.8/conf/zoo.cfg
  - /tmp/zookeeper/zookeeper-3.4.8/bin/zkServer.sh start
  - sed -i "s/zookeepernodes: .*/zookeepernodes: ['localhost:2181']/" conf/scalephant.yaml
  - echo "#####################################################################"
  - cat conf/scalephant.yaml
  - echo "#####################################################################"

cache:
  directories:
  - $HOME/.m2