language: java
jdk:
  - oraclejdk8

# Don't use the Travis Container-Based Infrastructure (jobs are killed during execution)
sudo: true

before_install:
  # Install zookeeper
  - mkdir /tmp/zookeeper
  - wget http://www.eu.apache.org/dist/zookeeper/zookeeper-3.4.8/zookeeper-3.4.8.tar.gz
  - tar xzf zookeeper-3.4.8.tar.gz -C /tmp/zookeeper
  - cp /tmp/zookeeper/zookeeper-3.4.8/conf/zoo_sample.cfg /tmp/zookeeper/zookeeper-3.4.8/conf/zoo.cfg
  - /tmp/zookeeper/zookeeper-3.4.8/bin/zkServer.sh start
  # Change config
  - sed -i "s/zookeepernodes:.*/zookeepernodes:\ ['localhost:2181']/" conf/bboxdb.yaml
  - sed -i "s|rootDirectory:.*|rootDirectory:\ /tmp/bboxdb_test|" conf/bboxdb.yaml
  - sed -i "s|dataDirectory:.*|dataDirectory:\ /tmp/bboxdb_test/data|" conf/bboxdb.yaml
  - echo "#####################################################################"
  - cat conf/bboxdb.yaml
  - echo "#####################################################################"
  # Create required directories
  - mkdir -p /tmp/bboxdb_test/data

cache:
  directories:
  - $HOME/.m2