theme: minima

title: 'BBoxDB'
subtitle: 'BBoxDB - The database for multidimensional big data'


sections: [
    ['doc', 'Documentation'],
    ['spec', 'Specification'],
    ['examples', 'Examples']
]
