title: 'BBoxDB'
subtitle: 'BBoxDB - The database for multidimensional big data'

navigation: 2

permalink: none

codeurl: 'https://github.com/jnidzwetzki/bboxdb'

baseurl: ''

sections: [
    ['doc', 'Documentation'],
    ['examples', 'Examples'],
    ['tools', 'Tools'],
    ['post', 'Posts']
]
